homeassistant:
  name: Home 
  latitude: -34.7148682
  longitude: -58.2891066 
  unit_system: metric
  time_zone: America/Argentina/Buenos_Aires
  elevation: 23

mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
  debug: true
  persistence: true
  version: '1.5'
  optimistic: true 

device_tracker:
  platform: ddwrt
  host: 192.168.x.x
  username: username
  password: password

switch:
  - platform: rpi_gpio
    ports:
      27: Table TV Lamp
    invert_logic: false
  - platform: tplink
    host: 192.168.20.116
    name: Wall
  - platform: tplink
    host: 192.168.20.131
    name: Foot Lamp
     
binary_sensor:
  platform: rpi_gpio
  ports:
    17: Motion Living
  pull_mode: "UP"
  bouncetime: 50
  invert_logic: false

input_boolean:
   cine_mode:
     initial: off
   alarm:
     initial: off

notify:
  name: pushover
  platform: pushover
  api_key: api_key
  user_key: user_key

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'
sun:

history:

frontend:

http:
  api_password: Password

discovery:

group: !include groups.yaml

scene: !include scenes.yaml

automation: !include automation.yaml

script: !include scripts.yaml
