---
- hosts: all
  vars:
    APP: "homeassistant"

  tasks:
    - name: install required packages
      action: apt pkg={{item}} state=installed install_recommends=yes
      with_items:
        - python-pip
        - python3-dev
        - virtualenv

    - name: create home assistant user
      user: name=hass state=present

    - name: create home assistant directory
      file: path=/home/hass/.homeassistant state=directory mode=0755 owner=hass

    - name: create virtualenv
      command: virtualenv -p python3 /home/hass

    - stat: path=/home/hass/bin/hass
      register: st

    - name: install homeassistant
      pip: name=homeassistant virtualenv=/home/hass
      when: not st.stat.exists

    - name: clone git config
      git: repo=https://github.com/juanviola/home-automation.git dest=/home/hass/home-automation update=yes

    - name: create autostart script
      copy: src=/home/hass/home-automation/playbooks/home-assistant.systemd dest=/etc/systemd/system/home-assistant@hass.service

    - stat: path=/home/hass/.homeassistant/configuration.yaml
      register: st

    - name: copy config files 
      command: bash -c "cp -R /home/hass/home-automation/homeassistant/* /home/hass/.homeassistant"
      when: not st.stat.exists

    - name: reload the daemon 
      command: systemctl --system daemon-reload

    - name: register the service 
      command: systemctl enable home-assistant@hass

    - debug: msg="To start HA run [ systemctl start home-assistant@hass ]"

