---
- hosts: all
  vars:
    APP: "homeassistant"

  tasks:
    - name: install required packages
      action: apt pkg={{item}} state=installed install_recommends=yes
      with_items:
        - python-pip
        - python3-dev
        - python3-pip

    - name: create homeassistant directory
      file: path=/root/.homeassistant state=directory mode=0755 owner=root

    - name: install home assistant
      pip: name=homeassistant executable=pip3 

    - stat: path=/root/home-automation
      register: st

    - name: clone git config
      git: repo=https://github.com/juanviola/home-automation.git dest=/root/home-automation update=yes
      when: not st.stat.exists
        
    - name: create autostart script
      copy: src=/root/home-automation/playbooks/home-assistant.systemd dest=/etc/systemd/system/home-assistant@root.service

    - stat: path=/root/.homeassistant/configuration.yaml
      register: st

    - name: copy config files 
      copy: 
        src: /root/home-automation/homeassistant/
        dest: /root/.homeassistant/
        group: root
        owner: root
        force: yes 
      when: not st.stat.exists

    - name: reload the daemon 
      command: systemctl --system daemon-reload

    - name: register the service 
      command: systemctl enable home-assistant@root
      
    - cron:
      name: "sync configuration to USB"
      minute: "0"
      hour: "0"
      job: "rsync -a /root/.homeassistant /mnt/USB2T"

    - debug: msg="To start HA run [ systemctl start home-assistant@root ]"

