---
- hosts: all

  tasks:
    - service: name=ssh state=started

    - name: install required packages
      action: apt pkg={{item}} state=installed install_recommends=yes
      with_items:
        - ntfs-3g

    - name: create usb mount directory
      file: path=/mnt/USB2T state=directory mode=0755 owner=root

    - name: Mount USB2T read-write
      mount: name=/mnt/USB2T src=/dev/sda1 fstype=ntfs-3g opts=rw state=present

    - synchronize:
        src: /var/log
        dest: /mnt/USB2T/log

    - service: name=rsyslog state=stopped

    - name: create symlink for /var/log
      file:
        src: /mnt/USB2T/log/log
        dest: /var/log
        state: link

    - service: name=rsyslog state=started
    
