---
- hosts: all

  tasks:
    - service: name=ssh state=started

    - name: install required packages
      action: apt pkg={{item}} state=installed install_recommends=yes
      with_items:
        - ntfs-3g
        - ssh
        - samba
        
    - service: name=samba state=stopped
    
    - name: backup samba original config
      command: mv /etc/samba/smb.conf /etc/samba/smb.conf.bak
      
    - name: copy samba config
      copy: src=/root/home-automation/samba/smb.conf dest=/etc/samba/smb.conf
    
    - service: name=ssh state=started 
    - command: update-rc.d ssh defaults

    - name: create usb mount directory
      file: path=/mnt/USB2T state=directory mode=0755 owner=root

    - name: Mount USB2T read-write
      mount: name=/mnt/USB2T src=/dev/sda1 fstype=ntfs-3g opts=rw state=present

    - synchronize:
        src: /var/log
        dest: /mnt/USB2T/log

    - service: name=rsyslog state=stopped

    - name: mount all
      command: mount -a

    - name: Move /var/log
      command: mv /var/log /var/log_OLD

    - name: create symlink for /var/log
      file:
        src: /mnt/USB2T/log/log
        dest: /var/log
        state: link

    - service: name=rsyslog state=started
    - service: name=samba state=started 
    - command: update-rc.d samba defaults
    
